#!/bin/sh
cd /bluenimble-platform

SERVICE_NAME=BlueNimble

PID_FILE=/bluenimble-platform/bluenimble-pid

CPATH=boot:boot/log4j-1.2.17.jar:boot/bluenimble-jvm-sdk-[version].jar:boot/bluenimble-server-boot-[version].jar
VMARGS=-server -Xms60m -Xmx384m -Djava.awt.headless=true

case $1 in
    start)
        echo "Starting BlueNimble Platform - Cluster Node ..."
        if [ ! -f $PID_PATH_NAME ]; then
            nohup java $VMARGS -cp $CPATH com.bluenimble.platform.server.boot.BlueNimble /tmp 2>> /dev/null >> /dev/null &
                        echo $! > $PID_FILE
            echo "$SERVICE_NAME started."
        else
            echo "$SERVICE_NAME is already running!"
        fi
    ;;
    stop)
        echo "Stopping BlueNimble Platform - Cluster Node..."
        if [ -f $PID_FILE ]; then
            PID=$(cat $PID_FILE);
            echo "$SERVICE_NAME stopping..."
            kill $PID;
            echo "$SERVICE_NAME stopped."
            rm $PID_FILE
        else
            echo "$SERVICE_NAME is not running!"
        fi
    ;;
    restart)
        if [ -f $PID_FILE ]; then
            PID=$(cat $PID_FILE);
	        echo "Stopping BlueNimble Platform - Cluster Node..."
            kill $PID;
            echo "$SERVICE_NAME stopped.";
            rm $PID_FILE
	        echo "Starting BlueNimble Platform - Cluster Node..."
            nohup java $VMARGS -cp $CPATH com.bluenimble.platform.server.boot.BlueNimble /tmp 2>> /dev/null >> /dev/null &
                        echo $! > $PID_PATH_NAME
            echo "$SERVICE_NAME started."
        else
            echo "$SERVICE_NAME is not running!"
        fi
    ;;
esac 